from django.urls import path
from .views.analyzer import (
    analyze_line_details_api,
    analyze_log_api,
    edge_addon_redirect_view,
    log_analyzer_view,
    persist_pending_rule_changes_api,
    preview_pending_rule_changes_api,
    update_analyzed_line_status_api,
    uploaded_log_cached_analysis_api,
)
from .views.auth import change_password_view, frst_download_view, help_view, login_view, logout_view, profile_view
from .views.fixlists import (
    copy_to_clipboard_api,
    create_fixlist_view,
    dashboard_view,
    download_fixlist,
    fixlists_trash_view,
    shared_fixlist_view,
    view_fixlist,
)
from .views.infection_cases import (
    create_infection_case_view,
    infection_case_add_items_view,
    infection_case_confirm_username_change_view,
    infection_case_delete_view,
    infection_case_download_logs_view,
    infection_cases_view,
    view_infection_case,
)
from .views.log_search import log_search_download_view, log_search_view
from .views.log_type_rules import (
    add_log_type_rule_view,
    delete_log_type_rule_view,
    edit_log_type_rule_view,
    log_type_rules_view,
    test_log_type_api,
    toggle_log_type_rule_view,
)
from .views.rules import add_rule_view, rules_view, test_rule_api
from .views.snippets import snippets_api, snippets_toggle_analyzer_api, snippets_view
from .views.speeches import speeches_api, speeches_toggle_analyzer_api, speeches_view
from .views.statistics import statistics_view
from .views.uploads import (
    diff_uploaded_logs_view,
    download_uploaded_log,
    upload_log_view,
    uploaded_log_content_api,
    uploaded_logs_view,
    uploads_trash_view,
    view_uploaded_log,
)

urlpatterns = [
    path('', login_view, name='login'),
    path('upload/<str:helper_username>/', upload_log_view, name='upload_log_for_helper'),
    path('upload/', upload_log_view, name='upload_log'),
    path('account/password/', change_password_view, name='change_password'),
    path('account/profile/', profile_view, name='profile'),
    path('help/', help_view, name='help'),
    path('frst-download/', frst_download_view, name='frst_download'),
    path('fixes/', dashboard_view, name='dashboard'),
    path('uploads/', uploaded_logs_view, name='uploaded_logs'),
    path('uploads/trash/', uploads_trash_view, name='uploads_trash'),
    # Must stay above the <str:upload_id> route, which would otherwise match 'search'.
    path('uploads/search/', log_search_view, name='log_search'),
    path('uploads/search/download/', log_search_download_view, name='log_search_download'),
    path('uploads/<str:upload_id>/', view_uploaded_log, name='view_uploaded_log'),
    path('uploads/<str:upload_id>/download/', download_uploaded_log, name='download_uploaded_log'),
    path('uploads/diff/<str:id1>/<str:id2>/', diff_uploaded_logs_view, name='diff_uploaded_logs'),
    path('fixes/trash/', fixlists_trash_view, name='fixlists_trash'),
    path('fixes/create/', create_fixlist_view, name='create_fixlist'),
    path('cases/', infection_cases_view, name='infection_cases'),
    path('cases/create/', create_infection_case_view, name='create_infection_case'),
    path('cases/<str:case_id>/', view_infection_case, name='view_infection_case'),
    path('cases/<str:case_id>/download-logs/', infection_case_download_logs_view, name='infection_case_download_logs'),
    path('cases/<str:case_id>/add-items/', infection_case_add_items_view, name='infection_case_add_items'),
    path('cases/<str:case_id>/confirm-username-change/', infection_case_confirm_username_change_view, name='infection_case_confirm_username_change'),
    path('cases/<str:case_id>/delete/', infection_case_delete_view, name='infection_case_delete'),
    path('analyze/', log_analyzer_view, name='log_analyzer'),
    path('api/uploaded-logs/<str:upload_id>/content/', uploaded_log_content_api, name='uploaded_log_content_api'),
    path('api/uploaded-logs/<str:upload_id>/cached-analysis/', uploaded_log_cached_analysis_api, name='uploaded_log_cached_analysis_api'),
    path('api/analyze-log/', analyze_log_api, name='analyze_log_api'),
    path('api/analyze-log/line-details/', analyze_line_details_api, name='analyze_line_details_api'),
    path('api/analyze-log/status/', update_analyzed_line_status_api, name='update_analyzed_line_status_api'),
    path('api/edge-addon/<str:crxid>/', edge_addon_redirect_view, name='edge_addon_redirect'),
    path('api/fixlist/rules-preview/', preview_pending_rule_changes_api, name='preview_pending_rule_changes_api'),
    path('api/fixlist/rules-persist/', persist_pending_rule_changes_api, name='persist_pending_rule_changes_api'),
    path('fixes/snippets/', snippets_view, name='snippets'),
    path('speeches/', speeches_view, name='speeches'),
    path('rules/', rules_view, name='rules'),
    path('rules/add/', add_rule_view, name='add_rule'),
    path('api/rules/test/', test_rule_api, name='test_rule_api'),
    path('log-types/', log_type_rules_view, name='log_type_rules'),
    path('log-types/add/', add_log_type_rule_view, name='add_log_type_rule'),
    path('log-types/<int:pk>/edit/', edit_log_type_rule_view, name='edit_log_type_rule'),
    path('log-types/<int:pk>/delete/', delete_log_type_rule_view, name='delete_log_type_rule'),
    path('log-types/<int:pk>/toggle/', toggle_log_type_rule_view, name='toggle_log_type_rule'),
    path('api/log-types/test/', test_log_type_api, name='test_log_type_api'),
    path('api/snippets/', snippets_api, name='snippets_api'),
    path('api/snippets/toggle-analyzer/', snippets_toggle_analyzer_api, name='snippets_toggle_analyzer_api'),
    path('api/speeches/', speeches_api, name='speeches_api'),
    path('api/speeches/toggle-analyzer/', speeches_toggle_analyzer_api, name='speeches_toggle_analyzer_api'),
    path('fixes/<int:pk>/', view_fixlist, name='view_fixlist'),
    path('share/<str:token>/', shared_fixlist_view, name='shared_fixlist'),
    path('download/<str:token>/', download_fixlist, name='download_fixlist'),
    path('api/copy/<str:token>/', copy_to_clipboard_api, name='copy_api'),
    path('stats/', statistics_view, name='statistics'),
    path('logout/', logout_view, name='logout'),
]
