from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('upload/<str:helper_username>/', views.upload_log_view, name='upload_log_for_helper'),
    path('upload/', views.upload_log_view, name='upload_log'),
    path('account/password/', views.change_password_view, name='change_password'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('uploads/', views.uploaded_logs_view, name='uploaded_logs'),
    path('uploads/trash/', views.uploads_trash_view, name='uploads_trash'),
    path('uploads/<str:upload_id>/', views.view_uploaded_log, name='view_uploaded_log'),
    path('uploads/diff/<str:id1>/<str:id2>/', views.diff_uploaded_logs_view, name='diff_uploaded_logs'),
    path('fixlists/trash/', views.fixlists_trash_view, name='fixlists_trash'),
    path('fixlists/create/', views.create_fixlist_view, name='create_fixlist'),
    path('fixlists/analyze/', views.log_analyzer_view, name='log_analyzer'),
    path('api/uploaded-logs/<str:upload_id>/content/', views.uploaded_log_content_api, name='uploaded_log_content_api'),
    path('api/analyze-log/', views.analyze_log_api, name='analyze_log_api'),
    path('api/analyze-log/line-details/', views.analyze_line_details_api, name='analyze_line_details_api'),
    path('api/analyze-log/status/', views.update_analyzed_line_status_api, name='update_analyzed_line_status_api'),
    path('api/fixlist/rules-preview/', views.preview_pending_rule_changes_api, name='preview_pending_rule_changes_api'),
    path('api/fixlist/rules-persist/', views.persist_pending_rule_changes_api, name='persist_pending_rule_changes_api'),
    path('fixlists/snippets/', views.snippets_view, name='snippets'),
    path('rules/', views.rules_view, name='rules'),
    path('rules/add/', views.add_rule_view, name='add_rule'),
    path('api/rules/test/', views.test_rule_api, name='test_rule_api'),
    path('api/snippets/', views.snippets_api, name='snippets_api'),
    path('fixlist/<int:pk>/', views.view_fixlist, name='view_fixlist'),
    path('share/<str:token>/', views.shared_fixlist_view, name='shared_fixlist'),
    path('download/<str:token>/', views.download_fixlist, name='download_fixlist'),
    path('api/copy/<str:token>/', views.copy_to_clipboard_api, name='copy_api'),
    path('logout/', views.logout_view, name='logout'),
]
