# Generated by Django 4.2 on 2026-03-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0011_uploadedlog_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedlog',
            name='upload_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
