# Generated by Django 4.2 on 2026-03-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0013_fixlist_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedlog',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=18),
        ),
    ]
