# Generated by Django 4.2 on 2026-03-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0014_add_content_hash_to_uploadedlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedlog',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
