# Generated by Django 4.2 on 2026-03-23 04:58

from django.db import migrations, models


def rename_fixlist_to_fixlog(apps, schema_editor):
    UploadedLog = apps.get_model('fixlist', 'UploadedLog')
    UploadedLog.objects.filter(log_type='Fixlist').update(log_type='Fixlog')


def rename_fixlog_to_fixlist(apps, schema_editor):
    UploadedLog = apps.get_model('fixlist', 'UploadedLog')
    UploadedLog.objects.filter(log_type='Fixlog').update(log_type='Fixlist')


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0015_fix_content_hash_max_length'),
    ]

    operations = [
        migrations.RunPython(rename_fixlist_to_fixlog, rename_fixlog_to_fixlist),
        migrations.AlterField(
            model_name='uploadedlog',
            name='log_type',
            field=models.CharField(choices=[('FRST', 'FRST'), ('Addition', 'Addition'), ('FRST&Addition', 'FRST&Addition'), ('Fixlog', 'Fixlog'), ('Unknown', 'Unknown')], default='Unknown', max_length=16),
        ),
    ]
