# Generated by Django 4.2 on 2026-03-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0016_rename_fixlist_to_fixlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedlog',
            name='fixlog_error',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedlog',
            name='fixlog_not_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedlog',
            name='fixlog_success',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedlog',
            name='fixlog_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
