# Generated by Django 4.2 on 2026-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0018_fixlistsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlistsnippet',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
