# Generated by Django 4.2 on 2026-03-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0019_add_snippet_is_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationrule',
            name='match_type',
            field=models.CharField(choices=[('exact', 'Exact line'), ('substring', 'Substring'), ('regex', 'Regex'), ('filepath', 'File path'), ('parsed', 'Parsed')], max_length=16),
        ),
        migrations.AlterField(
            model_name='classificationrule',
            name='status',
            field=models.CharField(choices=[('B', 'Malware'), ('P', 'Potentially unwanted'), ('C', 'Clean'), ('!', 'Warning'), ('G', 'Grayware'), ('S', 'Security software'), ('I', 'Informational'), ('J', 'Junk'), ('?', 'Unknown')], max_length=1),
        ),
    ]
