# Generated by Django 4.2 on 2026-04-04 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixlist', '0023_rename_fixlist_title_to_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, db_index=True, max_length=24, unique=True)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('symptom_description', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infection_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfectionCaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_case_logs', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_links', to='fixlist.infectioncase')),
                ('uploaded_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infection_case_links', to='fixlist.uploadedlog')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='InfectionCaseFixlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_case_fixlists', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixlist_links', to='fixlist.infectioncase')),
                ('fixlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infection_case_links', to='fixlist.fixlist')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='infectioncaselog',
            constraint=models.UniqueConstraint(fields=('case', 'uploaded_log'), name='unique_case_uploaded_log'),
        ),
        migrations.AddConstraint(
            model_name='infectioncasefixlist',
            constraint=models.UniqueConstraint(fields=('case', 'fixlist'), name='unique_case_fixlist'),
        ),
        migrations.AddIndex(
            model_name='infectioncase',
            index=models.Index(fields=['owner', '-created_at'], name='fixlist_inf_owner_i_760662_idx'),
        ),
        migrations.AddIndex(
            model_name='infectioncase',
            index=models.Index(fields=['username', '-created_at'], name='fixlist_inf_usernam_bea1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='infectioncase',
            index=models.Index(fields=['deleted_at'], name='fixlist_inf_deleted_035b2e_idx'),
        ),
    ]
