# Generated by Django 4.2 on 2026-04-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0024_infectioncase_infectioncaselog_infectioncasefixlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectioncase',
            name='auto_assign_new_items',
            field=models.BooleanField(default=True),
        ),
    ]
