# Generated by Django 4.2 on 2026-04-04 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixlist', '0025_infectioncase_auto_assign_new_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionCaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='fixlist.infectioncase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infection_case_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='infectioncasenote',
            index=models.Index(fields=['case', 'created_at'], name='fixlist_inf_case_id_6eb16d_idx'),
        ),
        migrations.AddIndex(
            model_name='infectioncasenote',
            index=models.Index(fields=['deleted_at'], name='fixlist_inf_deleted_92313e_idx'),
        ),
    ]
