# Generated by Django 4.2 on 2026-04-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0027_infectioncasenote_anchor_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='infectioncasenote',
            new_name='fixlist_inf_case_id_4b5ed9_idx',
            old_name='fixlist_inf_case_id_6eb16d_idx',
        ),
        migrations.RenameIndex(
            model_name='infectioncasenote',
            new_name='fixlist_inf_deleted_78e735_idx',
            old_name='fixlist_inf_deleted_92313e_idx',
        ),
        migrations.AddField(
            model_name='infectioncasenote',
            name='anchor_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_notes', to='fixlist.infectioncasenote'),
        ),
    ]
