# Generated by Django 4.2 on 2026-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0028_add_anchor_note_to_infectioncasenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedlog',
            name='scan_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
