# Generated by Django 4.2 on 2026-04-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0029_add_scan_date_to_uploadedlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectioncase',
            name='is_training',
            field=models.BooleanField(default=False),
        ),
    ]
