# Generated by Django 4.2 on 2026-04-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0030_infectioncase_is_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlist',
            name='line_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
