# Generated by Django 4.2 on 2026-04-06 04:40

from django.db import migrations


def backfill_line_count(apps, schema_editor):
    Fixlist = apps.get_model('fixlist', 'Fixlist')
    for fixlist in Fixlist.objects.all().iterator():
        fixlist.line_count = len([l for l in (fixlist.content or '').splitlines() if l.strip()])
        fixlist.save(update_fields=['line_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0031_fixlist_line_count'),
    ]

    operations = [
        migrations.RunPython(backfill_line_count, migrations.RunPython.noop),
    ]
