# Generated by Django 4.2 on 2026-04-07 00:00

from django.db import migrations, models


def backfill_public_fixlists(apps, schema_editor):
    Fixlist = apps.get_model('fixlist', 'Fixlist')
    Fixlist.objects.filter(is_public=False).update(is_public=True)


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0032_backfill_fixlist_line_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixlist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(backfill_public_fixlists, migrations.RunPython.noop),
    ]
