# Generated by Django 4.2 on 2026-04-08 00:00

import re

from django.db import migrations


FIREFOX_PROFILE_RE = re.compile(r"(?i)(\\mozilla\\firefox\\profiles\\)[^\\]+")


def normalize_path(path: str) -> str:
    default_username = "username"
    path = path or ""
    if len(path) >= 2 and path[1] == ":" and not path.startswith("C:"):
        path = "C:" + path[2:]
    path = re.sub(r"(?i)(C:\\Users\\)[^\\]+", r"\1" + default_username, path)
    return FIREFOX_PROFILE_RE.sub(r"\1profile", path)


def backfill_normalized_filepaths(apps, schema_editor):
    ClassificationRule = apps.get_model('fixlist', 'ClassificationRule')
    ParsedFilepathExclusion = apps.get_model('fixlist', 'ParsedFilepathExclusion')

    for rule in ClassificationRule.objects.all().iterator():
        source_path = (rule.filepath or '').strip()
        if not source_path and rule.match_type == 'filepath':
            source_path = (rule.source_text or '').strip()

        normalized = normalize_path(source_path).lower().strip() if source_path else ''
        if normalized != (rule.normalized_filepath or ''):
            rule.normalized_filepath = normalized
            rule.save(update_fields=['normalized_filepath'])

    kept_by_normalized_path = {}
    exclusions_to_delete = []

    for exclusion in ParsedFilepathExclusion.objects.order_by('pk').iterator():
        normalized = normalize_path((exclusion.normalized_filepath or '').strip()).lower().strip()
        existing = kept_by_normalized_path.get(normalized)
        if existing is None:
            if normalized != (exclusion.normalized_filepath or ''):
                exclusion.normalized_filepath = normalized
                exclusion.save(update_fields=['normalized_filepath'])
            kept_by_normalized_path[normalized] = exclusion
            continue

        merged_note = (existing.note or '').strip()
        incoming_note = (exclusion.note or '').strip()
        if incoming_note and incoming_note not in merged_note.split('\n\n'):
            merged_note = f"{merged_note}\n\n{incoming_note}".strip() if merged_note else incoming_note

        merged_enabled = existing.is_enabled or exclusion.is_enabled
        updated_fields = []
        if merged_note != (existing.note or ''):
            existing.note = merged_note
            updated_fields.append('note')
        if merged_enabled != existing.is_enabled:
            existing.is_enabled = merged_enabled
            updated_fields.append('is_enabled')
        if updated_fields:
            existing.save(update_fields=updated_fields)

        exclusions_to_delete.append(exclusion.pk)

    if exclusions_to_delete:
        ParsedFilepathExclusion.objects.filter(pk__in=exclusions_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0033_enable_public_sharing_default'),
    ]

    operations = [
        migrations.RunPython(backfill_normalized_filepaths, migrations.RunPython.noop),
    ]