# Generated by Django 4.2 on 2026-04-08 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0035_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlist',
            name='source_uploaded_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixlists', to='fixlist.uploadedlog'),
        ),
    ]
