# Generated by Django 4.2 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0036_fixlist_source_uploaded_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedlog',
            name='detected_encoding',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
