# Generated by Django 4.2 on 2026-04-15 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixlist', '0037_uploadedlog_detected_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlistsnippet',
            name='analyzer_users',
            field=models.ManyToManyField(blank=True, related_name='analyzer_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
