# Generated by Django 4.2 on 2026-04-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0038_add_snippet_analyzer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlistsnippet',
            name='category',
            field=models.CharField(default='Generic', max_length=255),
        ),
    ]
