# Generated by Django 4.2 on 2026-04-15 12:58

from django.db import migrations


def rename_generic_lowercase(apps, schema_editor):
    FixlistSnippet = apps.get_model('fixlist', 'FixlistSnippet')
    FixlistSnippet.objects.filter(category='Generic').update(category='generic')


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0039_add_snippet_category'),
    ]

    operations = [
        migrations.RunPython(rename_generic_lowercase, migrations.RunPython.noop),
    ]
