# Generated by Django 4.2 on 2026-04-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0045_reparse_runkey_parsed_entry_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixlistsnippet',
            name='category',
            field=models.CharField(default='generic', max_length=255),
        ),
    ]
