# Generated by Django 4.2 on 2026-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0046_alter_fixlistsnippet_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixlistStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('owner_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('owner_username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('line_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedLogStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('owner_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('owner_username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('recipient_username', models.CharField(blank=True, default='', max_length=150)),
                ('log_type', models.CharField(choices=[('FRST', 'FRST'), ('Addition', 'Addition'), ('FRST&Addition', 'FRST&Addition'), ('Fixlog', 'Fixlog'), ('Unknown', 'Unknown')], db_index=True, default='Unknown', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('total_line_count', models.PositiveIntegerField(default=0)),
                ('count_malware', models.PositiveIntegerField(default=0)),
                ('count_pup', models.PositiveIntegerField(default=0)),
                ('count_clean', models.PositiveIntegerField(default=0)),
                ('count_warning', models.PositiveIntegerField(default=0)),
                ('count_grayware', models.PositiveIntegerField(default=0)),
                ('count_security', models.PositiveIntegerField(default=0)),
                ('count_info', models.PositiveIntegerField(default=0)),
                ('count_junk', models.PositiveIntegerField(default=0)),
                ('count_unknown', models.PositiveIntegerField(default=0)),
                ('fixlog_total', models.PositiveIntegerField(default=0)),
                ('fixlog_success', models.PositiveIntegerField(default=0)),
                ('fixlog_not_found', models.PositiveIntegerField(default=0)),
                ('fixlog_error', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
