# Generated by Django 4.2 on 2026-05-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0050_classificationrule_priority_rebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedlog',
            name='count_alert',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedlogstat',
            name='count_alert',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
