# Generated by Django 4.2 on 2026-05-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0051_add_count_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_token', models.CharField(blank=True, default='', help_text='Shared secret for guest access to the log analyzer and help page. Leave blank to disable guest access entirely.', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
