# Generated by Django 4.2 on 2026-05-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0053_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationrule',
            name='attributes',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
