# Generated by Django 4.2 on 2026-05-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0054_classificationrule_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationrule',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
