# Generated by Django 4.2 on 2026-05-25 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0055_classificationrule_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedLogAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('source_content_hash', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_analysis', to='fixlist.uploadedlog')),
            ],
        ),
    ]
