# Generated by Django 4.2 on 2026-05-27 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixlist', '0059_rename_reddit_username_to_forum_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedlog',
            name='log_type',
            field=models.CharField(choices=[('FRST', 'FRST'), ('Addition', 'Addition'), ('FRST&Addition', 'FRST&Addition'), ('Fixlog', 'Fixlog'), ('Shortcut', 'Shortcut'), ('ESET', 'ESET'), ('AdwCleaner', 'AdwCleaner'), ('HitmanPro', 'HitmanPro'), ('Emsisoft', 'Emsisoft'), ('Malwarebytes', 'Malwarebytes'), ('Unknown', 'Unknown')], default='Unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadedlogstat',
            name='log_type',
            field=models.CharField(choices=[('FRST', 'FRST'), ('Addition', 'Addition'), ('FRST&Addition', 'FRST&Addition'), ('Fixlog', 'Fixlog'), ('Shortcut', 'Shortcut'), ('ESET', 'ESET'), ('AdwCleaner', 'AdwCleaner'), ('HitmanPro', 'HitmanPro'), ('Emsisoft', 'Emsisoft'), ('Malwarebytes', 'Malwarebytes'), ('Unknown', 'Unknown')], db_index=True, default='Unknown', max_length=16),
        ),
        migrations.CreateModel(
            name='LogTypeDetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('log_type', models.CharField(choices=[('FRST', 'FRST'), ('Addition', 'Addition'), ('Fixlog', 'Fixlog'), ('Shortcut', 'Shortcut'), ('ESET', 'ESET'), ('AdwCleaner', 'AdwCleaner'), ('HitmanPro', 'HitmanPro'), ('Emsisoft', 'Emsisoft'), ('Malwarebytes', 'Malwarebytes')], max_length=16)),
                ('pattern', models.TextField()),
                ('scope', models.CharField(choices=[('full', 'Anywhere in content'), ('start', 'Header (first 4KB)')], default='full', max_length=8)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_log_type_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='logtypedetectionrule',
            index=models.Index(fields=['is_enabled', 'priority'], name='fixlist_log_is_enab_cf3e35_idx'),
        ),
    ]
