# Generated by Django 4.2 on 2026-05-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0063_fix_german_dutch_frst_patterns'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTypeBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('color', models.CharField(default='#cccccc', max_length=7)),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='logtypedetectionrule',
            name='log_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='uploadedlog',
            name='log_type',
            field=models.CharField(default='Unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='uploadedlogstat',
            name='log_type',
            field=models.CharField(db_index=True, default='Unknown', max_length=32),
        ),
    ]
