# Generated by Django 4.2 on 2026-05-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0065_seed_log_type_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtypedetectionrule',
            name='scope',
            field=models.CharField(choices=[('full', 'Anywhere in content'), ('start', 'Header (first 4KB)')], default='start', max_length=8),
        ),
    ]
