# Generated by Django 4.2 on 2026-05-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0066_default_scope_to_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationrule',
            name='match_type',
            field=models.CharField(choices=[('exact', 'Exact line'), ('substring', 'Substring'), ('regex', 'Regex'), ('filepath', 'File path'), ('parsed', 'Parsed'), ('script', 'Python script')], max_length=16),
        ),
    ]
