# Generated by Django 4.2 on 2026-06-30 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixlist', '0067_alter_classificationrule_match_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classificationrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='whole_log',
            field=models.BooleanField(default=False, help_text='Alert rules only: evaluate once against the whole log instead of per line.'),
        ),
        migrations.AlterUniqueTogether(
            name='classificationrule',
            unique_together={('owner', 'status', 'match_type', 'source_text', 'whole_log')},
        ),
    ]
