# Generated by Django 4.2 on 2026-08-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0069_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlist',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Protected fixlists cannot be trashed, permanently deleted, or auto-purged.'),
        ),
        migrations.AddField(
            model_name='uploadedlog',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Protected logs cannot be trashed, permanently deleted, merged away, or auto-purged.'),
        ),
    ]
