# Generated by Django 4.2 on 2026-08-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0070_add_deletion_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlist',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
