# Generated by Django 4.2 on 2026-08-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0071_fixlist_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='infectioncasefixlist',
            name='show_response',
            field=models.BooleanField(default=True),
        ),
    ]
