# Generated by Django 4.2 on 2026-08-22 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def link_existing_responses(apps, schema_editor):
    """Give every response that is currently on a timeline its own link row.

    Before this migration a response showed in a case whenever its fixlist was
    linked and `show_response` was set, so those pairs become InfectionCaseResponse
    rows. `response_created_at` is backfilled from the fixlist's `updated_at`, the
    closest thing to a write time that exists for older rows.
    """
    Fixlist = apps.get_model('fixlist', 'Fixlist')
    InfectionCaseFixlist = apps.get_model('fixlist', 'InfectionCaseFixlist')
    InfectionCaseResponse = apps.get_model('fixlist', 'InfectionCaseResponse')

    for fixlist in Fixlist.objects.exclude(response='').only('id', 'updated_at'):
        Fixlist.objects.filter(pk=fixlist.pk).update(response_created_at=fixlist.updated_at)

    links = (
        InfectionCaseFixlist.objects
        .filter(show_response=True)
        .exclude(fixlist__response='')
        .select_related('fixlist')
    )
    InfectionCaseResponse.objects.bulk_create(
        [
            InfectionCaseResponse(case_id=link.case_id, fixlist_id=link.fixlist_id, added_by_id=link.added_by_id)
            for link in links
            if link.fixlist.deleted_at is None
        ],
        ignore_conflicts=True,
    )


def unlink_responses(apps, schema_editor):
    apps.get_model('fixlist', 'InfectionCaseResponse').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixlist', '0072_infectioncasefixlist_show_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlist',
            name='response_created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='infectioncasenote',
            name='anchor_fixlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_notes', to='fixlist.infectioncasefixlist'),
        ),
        migrations.CreateModel(
            name='InfectionCaseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_case_responses', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_links', to='fixlist.infectioncase')),
                ('fixlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infection_case_response_links', to='fixlist.fixlist')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.AddField(
            model_name='infectioncasenote',
            name='anchor_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_notes', to='fixlist.infectioncaseresponse'),
        ),
        migrations.AddConstraint(
            model_name='infectioncaseresponse',
            constraint=models.UniqueConstraint(fields=('case', 'fixlist'), name='unique_case_response'),
        ),
        # Must run while show_response still exists.
        migrations.RunPython(link_existing_responses, unlink_responses),
        migrations.RemoveField(
            model_name='infectioncasefixlist',
            name='show_response',
        ),
    ]
