# Generated by Django 4.2 on 2026-09-28 04:18

from django.db import migrations, models


def keep_existing_informational_substring_rules_whole_line(apps, schema_editor):
    """Existing substring rules switch to colouring just the matched text, like
    new ones -- except Informational (I) rules, which keep colouring the whole
    line. `update()` leaves `updated_at` alone, so the rules list's "recently
    edited" order is unaffected."""
    Rule = apps.get_model('fixlist', 'ClassificationRule')
    Rule.objects.filter(match_type='substring', status='I').update(color_whole_line=True)


class Migration(migrations.Migration):

    dependencies = [
        ('fixlist', '0073_remove_infectioncasefixlist_show_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationrule',
            name='color_whole_line',
            field=models.BooleanField(default=False, help_text='Substring rules only: colour the whole analyzer line instead of just the matched text.'),
        ),
        migrations.RunPython(
            keep_existing_informational_substring_rules_whole_line,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
